spring:
  application:
    name: task_management
  datasource:
    url: jdbc:postgresql://localhost:5432/time_managementdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    locations: classpath:db/migration
  logging:
    level:
      org.hibernate.SQL: debug